name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or 18 if 16 gives issues

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          find ./giftlink-backend -name app.js -exec jshint {} +
          find ./giftlink-backend -name auth.js -exec jshint {} +
          find ./giftlink-backend -name giftRoutes.js -exec jshint {} +
          find ./giftlink-backend -name searchRoutes.js -exec jshint {} +
          echo "Linted all the js files successfully"

  client_build: # REMOVE this entire block if you DO NOT have a client build
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or 18
      - name: Run build
        run: |
          cd giftlink-frontend # Change to your client directory if different
          npm install
          npm run build # Change to your client build command if different
          echo "Client-side build successfully"
